version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - kafka
    command:
      - sh
      - -c
      - |
        /etc/confluent/docker/run & 
        sleep 10 && 
        kafka-topics --create --topic my_topic_1 --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1
        kafka-topics --create --topic my_topic_2 --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1
        wait

networks:
  kafka:
    driver: bridge
